---
title: "Problem Set 1"
author: "whomsoever"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stats)
```

# Introduction 

This document was produced by R using R Markdown. The convenience of using R Markdown is you can present code and text in the same document. The first problem will introduce you to the R programming environment. If you have not yet installed RStudio, do that now -- https://www.rstudio.com/download.  

For questions that require coding, please present your code in code chunks -- these are the grey boxes. To insert a new code chunk, click `Code > Insert Chunk` in the menu bar (there are also shortcuts for this). Everything outside code chunks will appear as text in your output document. For questions that do not require coding, type your answers in the spaces provided. If there is heavy math involved you may present handwritten answers.  

To compile a markdown document (i.e. create the output document), click 'Knit'. For pdf output, you will need to have some form of TeX installed on your computer -- https://www.latex-project.org/get/. Alternatively you can specify html output, by writing `html_document` in the output section at the very top of the document, which does not require TeX.  

For tips on R Markdown syntax, check out the cheatsheet we have provided.  

Any time you are confused about a command in R, use `help()` to bring up the relevant documentation. If you get an error message you don't understand, google it -- it is very likely someone else has encountered the same error and written about it on Stack Overflow or the like.  

The packages used in this problem set are:

- `tidyverse` (is a set of eight packages)
- `stats`

Make sure these are loaded in the setup chunk using the `library()` command. If you get the error message "there is no package called 'XXX'", you need to first install the package, using `install.packages('XXX')`, then load it into the session using `library()`. 



# I -- Warmup

In this problem set you will use 





