---
title: 'introstats'
output:
  tufte::tufte_html:
    tufte_features: ['fonts','background']
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = FALSE)
library(tidyverse)
library(ggplot2)
library(knitr)
library(kableExtra)
library(extraDistr)
library(gridExtra)
library(latex2exp)
library(moments)
library(bookdown)
library(rsconnect)
```

\newcommand{\E}{\text{E}}
\newcommand{\Var}{\text{Var}}
\newcommand{\SD}{\text{SD}}
\newcommand{\SE}{\text{SE}}
\newcommand{\Cov}{\text{Cov}}
\newcommand{\Cor}{\text{Cor}}
\renewcommand{\P}{\text{P}}
\newcommand{\pd}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\sumin}{\sum_i^n}
\newcommand{\Bias}{\text{Bias}}

\newcommand{\head}[2]{\text{#1} \hspace{0.5cm} \text{#2}}

--- 

<a href="./about.html">about</a>  
<a href="./problemsets.html">problem sets</a>  
<a href="./datasets.html">data</a>  
<a href="./addenda.html">addenda</a>

\ 

### PART I --- ELEMENTS

- chapter 1 -- <a href="./notes/c1-R.html">The R Environment</a>  
- chapter 2 -- <a href="./notes/c2-getting-started.html">Getting Started with Data</a>  
- chapter 3 -- <a href="./notes/c3-wrangle-visualize.html">Wrangling and Visualizing Data</a>  
- chapter 4 -- <a href="./notes/c4-basic-analysis.html">Basic Data Analayis</a>  
- chapter 5 -- <a href="./notes/c5-basic-modeling.html">Basic Data Modeling</a>   
- chapter 6 -- <a href="./notes/c6-more-models.html">More Modeling Techniques</a>   

### PART I $\frac 12$ --- A PROBABILISTIC BRIDGE

- chapter 7 -- Elements of Probability
- chapter 8 -- The Algebra of Random Variables
- chapter 9 -- Distributions of Random Variables

### PART II --- VARIABILITY

- chapter 10 -- <a href="./notes/c10-sampling.html">Samples, Sampling, and Variability</a></li>
- chapter 11 -- <a href="./notes/c11-clt.html">The Central Limit Theorem</a></li>
- chapter 12 -- <a href="./notes/c12-intervals.html">Interval Estimators</a></li>
- chapter 13 -- <a href="./notes/c13-hyptests.html">Significance Tests</a></li>
- chapter 14 -- Joint Variability
- chapter 15 -- Variability in Linear Models
- chapter 16 -- The Assumptions of Linear Models
- chapter 17 -- Inference from Linear Models 

### PART III --- BIAS

- chapter 18 -- <a href="./notes/c17-validity-bias.html">Validity and Bias</a></li>
- chapter 19 -- Sampling Bias 
- chapter 20 -- Omitted Variable Bias
- chapter 21 -- Specification Bias
- chapter 22 -- Measurement Error Bias 

### PART IV --- MODEL SELECTION 

- chapter 23 -- Bias-Variance Tradeoff
- chapter 24 -- Model Selection Algorithms 
- ... 






